### ISSUE TITLE
Project and environment disappear

### ISSUE THREAD

**Issue by fatihaksoy59** [dromara/fast-request#101]
After closing and opening the ide, the values that I previously set are lost.
It gives the warning in the picture every time.

![image](https://user-images.githubusercontent.com/5838475/184294092-12254c45-15f7-4607-a1a2-873983687890.png)

**Comment by kings1990** [comment]
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/8969637/184294628-dc5d6659-ca0b-480f-a5e8-83423e5432c0.png">
<img width="694" alt="image" src="https://user-images.githubusercontent.com/8969637/184294672-14322d0d-00e7-4e94-b261-09e99c44a55f.png">
Did you add config here ?

**Comment by kings1990** [comment]
And what's your idea version

**Comment by fatihaksoy59** [comment]
i add it like this every time, version : IntelliJ IDEA 2022.1.2 (Community Edition)
![image](https://user-images.githubusercontent.com/5838475/184294865-f5030aee-14e5-45fc-b80c-b23ff9af9b48.png)

**Comment by fatihaksoy59** [comment]
by the way I have a error;

com.intellij.diagnostic.PluginException: Cannot init component state (componentName=fastRequest, componentClass=FastRequestComponent) [Plugin: io.github.kings1990.FastRequest]
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:148)
	at com.intellij.configurationStore.ComponentStoreWithExtraComponents.initComponent(ComponentStoreWithExtraComponents.kt:48)
	at com.intellij.serviceContainer.ComponentManagerImpl.initializeComponent$intellij_platform_serviceContainer(ComponentManagerImpl.kt:536)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:55)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:41)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:119)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:73)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:66)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:610)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:584)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at io.github.kings1990.plugin.fastrequest.config.FastRequestComponent.getInstance(L:80)
	at io.github.kings1990.plugin.fastrequest.cofig.II1lI1lII.<init>(L:67)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:47)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:891)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:51)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:41)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:119)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:73)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:66)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:610)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:584)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at io.github.kings1990.plugin.fastrequest.cofig.lll1lIl1l1l1l.<init>(L:161)
	at io.github.kings1990.plugin.fastrequest.cofig.lIIlllIllI.createToolWindowContent(L:85)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:529)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.scheduleContentInitializationIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:508)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doShowWindow(ToolWindowManagerImpl.kt:921)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl(ToolWindowManagerImpl.kt:861)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl$default(ToolWindowManagerImpl.kt:850)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.registerToolWindow$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:1025)
	at com.intellij.toolWindow.ToolWindowSetInitializer.createAndLayoutToolWindows(ToolWindowSetInitializer.kt:188)
	at com.intellij.toolWindow.ToolWindowSetInitializer.access$createAndLayoutToolWindows(ToolWindowSetInitializer.kt:83)
	at com.intellij.toolWindow.ToolWindowSetInitializer$initUi$1.accept(ToolWindowSetInitializer.kt:147)
	at com.intellij.toolWindow.ToolWindowSetInitializer$initUi$1.accept(ToolWindowSetInitializer.kt:83)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at com.intellij.toolWindow.ToolWindowSetInitializer$initUi$2.execute(ToolWindowSetInitializer.kt:156)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:750)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731)
	at java.base/java.util.concurrent.CompletableFuture.thenAcceptAsync(CompletableFuture.java:2117)
	at com.intellij.toolWindow.ToolWindowSetInitializer.initUi(ToolWindowSetInitializer.kt:141)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doInit(ToolWindowManagerImpl.kt:446)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.init(ToolWindowManagerImpl.kt:419)
	at com.intellij.toolWindow.InitToolWindowSetActivity$runActivity$2.run(ToolWindowSetInitializer.kt:72)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: com.intellij.util.xmlb.XmlSerializationException: Cannot deserialize class io.github.kings1990.plugin.fastrequest.model.FastRequestConfiguration
	at com.intellij.configurationStore.JdomSerializerImpl.deserialize(xmlSerializer.kt:99)
	at com.intellij.configurationStore.DefaultStateSerializerKt.deserializeState(DefaultStateSerializer.kt:29)
	at com.intellij.configurationStore.StateStorageBase.deserializeState(StateStorageBase.kt:35)
	at com.intellij.configurationStore.StateGetterImpl.getState(StorageBaseEx.kt:57)
	at com.intellij.configurationStore.ComponentStoreImpl.doInitComponent(ComponentStoreImpl.kt:423)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:373)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:119)
	... 81 more
Caused by: java.lang.UnsupportedOperationException
	at com.google.common.collect.ImmutableMap.clear(ImmutableMap.java:684)
	at com.intellij.util.xmlb.MapBinding.deserialize(MapBinding.java:209)
	at com.intellij.util.xmlb.MapBinding.deserializeList(MapBinding.java:168)
	at com.intellij.util.xmlb.Binding.deserializeList(Binding.java:25)
	at com.intellij.util.xmlb.OptionTagBinding.deserialize(OptionTagBinding.java:109)
	at com.intellij.util.xmlb.BasePrimitiveBinding.deserializeUnsafe(BasePrimitiveBinding.java:55)
	at com.intellij.util.xmlb.BeanBinding.deserializeInto(BeanBinding.java:246)
	at com.intellij.util.xmlb.BeanBinding.deserializeInto(BeanBinding.java:200)
	at com.intellij.util.xmlb.BeanBinding.deserialize(BeanBinding.java:143)
	at com.intellij.configurationStore.JdomSerializerImpl.deserialize(xmlSerializer.kt:93)
	... 87 more

**Comment by kings1990** [comment]
Hey can you upload the config file name fastRequest.xml? It maybe cause by you config error

[https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs](https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs)

<img width="812" alt="image" src="https://user-images.githubusercontent.com/8969637/184296505-04184d07-2487-4941-a23e-c5663cd0b7ec.png">

**Comment by kings1990** [comment]
```
<application>
  <component name="fastRequest">
    <option name="defaultDataMappingList">
      <list>
        <DataMapping>
          <option name="type" value="byte" />
          <option name="value" value="1" />
        </DataMapping>
        <DataMapping>
          <option name="type" value="java.lang.Byte" />
          <option name="value" value="1" />
        </DataMapping>
        <DataMapping>
          <option name="type" value="short" />
          <option name="value" value="1" />
        </DataMapping>
        <DataMapping>
          <option name="type" value="java.lang.Short" />
          <option name="value" value="1" />
        </DataMapping>
        <DataMapping>
          <option name="type" value="int" />
          <option name="value" value="1" />
        </DataMapping>
        <DataMapping>
          <option name="type" value="java.lang.Integer" />
          <option name="value" value="1" />
        </DataMapping>
        <DataMapping>
          <option name="type" value="long" />
          <option name="value" value="1" />
        </DataMapping>
        <DataMapping>
          <option name="type" value="java.lang.Long" />
          <option name="value" value="1" />
        </DataMapping>
        <DataMapping>
          <option name="type" value="char" />
          <option name="value" value="a" />
        </DataMapping>
        <DataMapping>
          <option name="type" value="java.lang.Character" />
          <option name="value" value="a" />
        </DataMapping>
        <DataMapping>
          <option name="type" value="float" />
          <option name="value" value="1" />
        </DataMapping>
        <DataMapping>
          <option name="type" value="java.lang.Float" />
          <option name="value" value="1" />
        </DataMapping>
        <DataMapping>
          <option name="type" value="double" />
          <option name="value" value="1" />
        </DataMapping>
        <DataMapping>
          <option name="type" value="java.lang.Double" />
          <option name="value" value="1" />
        </DataMapping>
        <DataMapping>
          <option name="type" value="boolean" />
          <option name="value" value="true" />
        </DataMapping>
        <DataMapping>
          <option name="type" value="java.lang.Boolean" />
          <option name="value" value="true" />
        </DataMapping>
        <DataMapping>
          <option name="type" value="java.math.BigDecimal" />
          <option name="value" value="1" />
        </DataMapping>
      </list>
    </option>
    <option name="randomStringLength" value="5" />
    <option name="statisticsDate" value="2022-08-11 10:01:25" />
    <option name="statisticsList">
      <list>
        <YearStatistics>
          <option name="totalActionCount" value="0" />
          <option name="year" value="2022" />
        </YearStatistics>
      </list>
    </option>
  </component>
</application>
```

Try to override by this config in fastRequest.xml and restart

**Comment by fatihaksoy59** [comment]
I used your config file, and it worked for me :) Thanks
