### ISSUE TITLE
刷新api列表时异常

### ISSUE THREAD

**Issue by zhangyan54545** [dromara/fast-request#184]
### Current Version
ide：2022.2.3
plugin：2022.2.7
### Operation steps
- It's best to provide a image

<img width="378" alt="image" src="https://user-images.githubusercontent.com/16732015/202595145-291f459d-5e41-4b7f-b646-4db2a423920e.png">

### Error Message

java.lang.NullPointerException: Cannot invoke "io.github.kings1990.plugin.fastrequest.cofig.fastRequest.I1lI1I1I(com.intellij.psi.PsiClass)" because "<local5>" is null
	at io.github.kings1990.plugin.fastrequest.cofig.implements.I1lI1I1I(L:132)
	at io.github.kings1990.plugin.fastrequest.cofig.l1I1ll1I1l$4.IIllII11Ill(L:292)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:149)
	at io.github.kings1990.plugin.fastrequest.cofig.l1I1ll1I1l$4.I1lI1I1I(L:271)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:915)
	at io.github.kings1990.plugin.fastrequest.cofig.l1I1ll1I1l$4.run(L:270)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by kings1990** [comment]
please update to 2022.2.9+
