### ISSUE TITLE
Navigate刷新API列表时报错

### ISSUE THREAD

**Issue by DroidEye2ONGU** [dromara/fast-request#190]
### Operation steps
在Kotlin/Java混编的SpringBoot项目中,Navigate选项中刷新API时报错

### Error Message

```
java.lang.ClassCastException: class com.intellij.psi.impl.source.PsiMethodImpl cannot be cast to class org.jetbrains.kotlin.asJava.elements.KtLightMethod (com.intellij.psi.impl.source.PsiMethodImpl is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @74501ac7; org.jetbrains.kotlin.asJava.elements.KtLightMethod is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @176c2515)
	at io.github.kings1990.plugin.fastrequest.cofig.getCode.lllI1lllIl1(L:446)
	at io.github.kings1990.plugin.fastrequest.cofig.implements.I1lI1I1I(L:97)
	at io.github.kings1990.plugin.fastrequest.cofig.l1I1ll1I1l$4.IIllII11Ill(L:292)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:167)
	at io.github.kings1990.plugin.fastrequest.cofig.l1I1ll1I1l$4.I1lI1I1I(L:271)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:847)
	at io.github.kings1990.plugin.fastrequest.cofig.l1I1ll1I1l$4.run(L:270)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:425)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:476)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:190)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:666)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:622)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:590)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:177)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by kings1990** [comment]
我的疑问是你一个类里面是不是写了kt又写了java 麻烦提供一下信息

**Comment by kings1990** [comment]
Ok, thanks for your feedback!

**Comment by kings1990** [comment]
Please upgrade to 2022.3.1+
