### ISSUE TITLE
316 ms to call on EDT I1lIII1ll1#update@MainMenu 

### ISSUE THREAD

**Issue by llTheBlankll** [dromara/fast-request#207]
```
com.intellij.diagnostic.PluginException: 316 ms to call on EDT I1lIII1ll1#update@MainMenu (io.github.kings1990.plugin.fastrequest.cofig.I1lIII1ll1). Revise AnAction.getActionUpdateThread property [Plugin: io.github.kings1990.FastRequest]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:83)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.computeOnEdt(ActionUpdater.java:255)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:203)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:161)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.updateActionReal(ActionUpdater.java:137)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$0(ActionUpdater.java:124)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.update(ActionUpdater.java:705)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.java:556)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$23(ActionUpdater.java:529)
	at com.intellij.util.containers.ContainerUtil.concat(ContainerUtil.java:1406)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup(ActionUpdater.java:529)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandActionGroup(ActionUpdater.java:309)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$14(ActionUpdater.java:377)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$15(ActionUpdater.java:396)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1111)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$tryRunReadActionAndCancelBeforeWrite$19(ActionUpdater.java:428)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:128)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.tryRunReadActionAndCancelBeforeWrite(ActionUpdater.java:424)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$16(ActionUpdater.java:396)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:366)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$17(ActionUpdater.java:395)
	at io.opentelemetry.context.Context.lambda$wrap$1(Context.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:243)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:216)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:205)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: java.lang.Throwable: EDT-trace-at-204-ms
		at io.github.kings1990.plugin.fastrequest.cofig.volatile.l111I1llllI(L:4062)
		at io.github.kings1990.plugin.fastrequest.cofig.volatile.Il1l1lll1(L:2506)
		at io.github.kings1990.plugin.fastrequest.cofig.volatile.double(L:3606)
		at io.github.kings1990.plugin.fastrequest.cofig.volatile.native(L)
		at io.github.kings1990.plugin.fastrequest.cofig.volatile.<init>(L:347)
		at io.github.kings1990.plugin.fastrequest.cofig.lIIll11I1lI.createToolWindowContent(L:105)
		at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:543)
		at com.intellij.openapi.wm.impl.ToolWindowImpl.getContentManager(ToolWindowImpl.kt:416)
		at io.github.kings1990.plugin.fastrequest.cofig.request.Il11l11III(L:54)
		at io.github.kings1990.plugin.fastrequest.cofig.I1lIII1ll1.update(L:84)
		at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$0(ActionUtil.java:157)
		at com.intellij.openapi.actionSystem.ex.ActionUtil$$Lambda$1068/0x0000000100cb9708.run(Unknown Source)
		at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:180)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater.doUpdate(ActionUpdater.java:720)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$updateActionReal$4(ActionUpdater.java:136)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$$Lambda$1537/0x00000001010a8fc0.get(Unknown Source)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$7(ActionUpdater.java:233)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$$Lambda$1731/0x000000010124b5c0.compute(Unknown Source)
		at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:68)
		at com.intellij.openapi.progress.ProgressManager$$Lambda$1441/0x0000000101079048.run(Unknown Source)
		at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
		at com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$1433/0x00000001010776a0.run(Unknown Source)
		at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
		at com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$1437/0x0000000101078248.compute(Unknown Source)
		at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
		at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
		at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
		at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
		at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
		at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:68)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$8(ActionUpdater.java:229)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$$Lambda$1730/0x000000010124a970.invoke(Unknown Source)
		at com.intellij.diagnostic.telemetry.TraceKt.computeWithSpan(trace.kt:123)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$9(ActionUpdater.java:225)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$$Lambda$1560/0x00000001010c6d38.get(Unknown Source)
		at io.opentelemetry.context.Context.lambda$wrapSupplier$8(Context.java:309)
		at io.opentelemetry.context.Context$$Lambda$1562/0x00000001010c77b0.get(Unknown Source)
		at com.intellij.openapi.actionSystem.impl.ActionUpdateEdtExecutor.lambda$computeOnEdt$0(ActionUpdateEdtExecutor.java:51)
		at com.intellij.openapi.actionSystem.impl.ActionUpdateEdtExecutor$$Lambda$1568/0x00000001010d06f0.run(Unknown Source)
		at com.intellij.openapi.actionSystem.impl.Utils.lambda$expandActionGroupFastTrack$5(Utils.java:323)
		at com.intellij.openapi.actionSystem.impl.Utils$$Lambda$1516/0x00000001010a2328.run(Unknown Source)
		at com.intellij.openapi.actionSystem.impl.Utils.runLoopAndWaitForFuture(Utils.java:836)
		at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroupFastTrack(Utils.java:321)
		at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroupImpl(Utils.java:240)
		at com.intellij.openapi.actionSystem.impl.Utils.lambda$expandActionGroup$0(Utils.java:205)
		at com.intellij.openapi.actionSystem.impl.Utils$$Lambda$4137/0x0000000102162b30.get(Unknown Source)
		at com.intellij.openapi.actionSystem.impl.Utils.computeWithRetries(Utils.java:866)
		at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:204)
		at com.intellij.ui.popup.ActionStepBuilder.appendActionsFromGroup(ActionStepBuilder.java:98)
		at com.intellij.ui.popup.ActionStepBuilder.buildGroup(ActionStepBuilder.java:70)
		at com.intellij.ui.popup.ActionPopupStep.createActionItems(ActionPopupStep.java:126)
		at com.intellij.ui.popup.ActionPopupStep.createActionsStep(ActionPopupStep.java:95)
		at com.intellij.ui.popup.ActionPopupStep.getSubStep(ActionPopupStep.java:240)
		at com.intellij.ui.popup.ActionPopupStep.onChosen(ActionPopupStep.java:221)
		at com.intellij.ui.popup.ActionPopupStep.onChosen(ActionPopupStep.java:213)
		at com.intellij.ui.popup.ActionPopupStep.onChosen(ActionPopupStep.java:25)
		at com.intellij.ui.popup.list.ListPopupImpl$MyMouseMotionListener.lambda$showSubMenu$0(ListPopupImpl.java:638)
		at com.intellij.ui.popup.list.ListPopupImpl$MyMouseMotionListener$$Lambda$5460/0x00000001028a1ad0.actionPerformed(Unknown Source)
		at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:311)
		at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:243)
		at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
		at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
		at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
		at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
		at java.base@17.0.5/java.security.AccessController.executePrivileged(AccessController.java:776)
		at java.base@17.0.5/java.security.AccessController.doPrivileged(AccessController.java:399)
		at java.base@17.0.5/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
		at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
		at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
		at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
		at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
		at com.intellij.ide.IdeEventQueue$$Lambda$626/0x000000010071a280.compute(Unknown Source)
		at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
		at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
		at com.intellij.ide.IdeEventQueue$$Lambda$625/0x000000010071a038.run(Unknown Source)
		at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
		at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
		at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
		at com.intellij.ide.IdeEventQueue$$Lambda$624/0x0000000100719df0.run(Unknown Source)
		at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
		at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
		at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
		at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
		at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
		at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
		at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
		at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
	Suppressed: java.lang.Throwable: EDT-trace-at-125-ms
		at java.base@17.0.5/java.util.Arrays.hashCode(Arrays.java:4499)
		at java.base@17.0.5/java.util.Objects.hash(Objects.java:133)
		at java.base@17.0.5/java.lang.invoke.MemberName.hashCode(MemberName.java:779)
		at java.base@17.0.5/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
		at java.base@17.0.5/java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:4133)
		at java.base@17.0.5/java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:615)
		at io.github.kings1990.plugin.fastrequest.cofig.true.Il11l11III(L:161)
		at io.github.kings1990.plugin.fastrequest.cofig.volatile.I1IIl11l1I1(L:3636)
		at io.github.kings1990.plugin.fastrequest.cofig.volatile.double(L:3582)
		at io.github.kings1990.plugin.fastrequest.cofig.volatile.native(L)
		at io.github.kings1990.plugin.fastrequest.cofig.volatile.<init>(L:347)
		at io.github.kings1990.plugin.fastrequest.cofig.lIIll11I1lI.createToolWindowContent(L:105)
		at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:543)
		at com.intellij.openapi.wm.impl.ToolWindowImpl.getContentManager(ToolWindowImpl.kt:416)
		at io.github.kings1990.plugin.fastrequest.cofig.request.Il11l11III(L:54)
		at io.github.kings1990.plugin.fastrequest.cofig.I1lIII1ll1.update(L:84)
		at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$0(ActionUtil.java:157)
		at com.intellij.openapi.actionSystem.ex.ActionUtil$$Lambda$1068/0x0000000100cb9708.run(Unknown Source)
		at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:180)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater.doUpdate(ActionUpdater.java:720)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$updateActionReal$4(ActionUpdater.java:136)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$$Lambda$1537/0x00000001010a8fc0.get(Unknown Source)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$7(ActionUpdater.java:233)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$$Lambda$1731/0x000000010124b5c0.compute(Unknown Source)
		at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:68)
		at com.intellij.openapi.progress.ProgressManager$$Lambda$1441/0x0000000101079048.run(Unknown Source)
		at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
		at com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$1433/0x00000001010776a0.run(Unknown Source)
		at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
		at com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$1437/0x0000000101078248.compute(Unknown Source)
		at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
		at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
		at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
		at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
		at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
		at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:68)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$8(ActionUpdater.java:229)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$$Lambda$1730/0x000000010124a970.invoke(Unknown Source)
		at com.intellij.diagnostic.telemetry.TraceKt.computeWithSpan(trace.kt:123)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$9(ActionUpdater.java:225)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$$Lambda$1560/0x00000001010c6d38.get(Unknown Source)
		at io.opentelemetry.context.Context.lambda$wrapSupplier$8(Context.java:309)
		at io.opentelemetry.context.Context$$Lambda$1562/0x00000001010c77b0.get(Unknown Source)
		at com.intellij.openapi.actionSystem.impl.ActionUpdateEdtExecutor.lambda$computeOnEdt$0(ActionUpdateEdtExecutor.java:51)
		at com.intellij.openapi.actionSystem.impl.ActionUpdateEdtExecutor$$Lambda$1568/0x00000001010d06f0.run(Unknown Source)
		at com.intellij.openapi.actionSystem.impl.Utils.lambda$expandActionGroupFastTrack$5(Utils.java:323)
		at com.intellij.openapi.actionSystem.impl.Utils$$Lambda$1516/0x00000001010a2328.run(Unknown Source)
		at com.intellij.openapi.actionSystem.impl.Utils.runLoopAndWaitForFuture(Utils.java:836)
		at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroupFastTrack(Utils.java:321)
		at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroupImpl(Utils.java:240)
		at com.intellij.openapi.actionSystem.impl.Utils.lambda$expandActionGroup$0(Utils.java:205)
		at com.intellij.openapi.actionSystem.impl.Utils$$Lambda$4137/0x0000000102162b30.get(Unknown Source)
		at com.intellij.openapi.actionSystem.impl.Utils.computeWithRetries(Utils.java:866)
		at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:204)
		at com.intellij.ui.popup.ActionStepBuilder.appendActionsFromGroup(ActionStepBuilder.java:98)
		at com.intellij.ui.popup.ActionStepBuilder.buildGroup(ActionStepBuilder.java:70)
		at com.intellij.ui.popup.ActionPopupStep.createActionItems(ActionPopupStep.java:126)
		at com.intellij.ui.popup.ActionPopupStep.createActionsStep(ActionPopupStep.java:95)
		at com.intellij.ui.popup.ActionPopupStep.getSubStep(ActionPopupStep.java:240)
		at com.intellij.ui.popup.ActionPopupStep.onChosen(ActionPopupStep.java:221)
		at com.intellij.ui.popup.ActionPopupStep.onChosen(ActionPopupStep.java:213)
		at com.intellij.ui.popup.ActionPopupStep.onChosen(ActionPopupStep.java:25)
		at com.intellij.ui.popup.list.ListPopupImpl$MyMouseMotionListener.lambda$showSubMenu$0(ListPopupImpl.java:638)
		at com.intellij.ui.popup.list.ListPopupImpl$MyMouseMotionListener$$Lambda$5460/0x00000001028a1ad0.actionPerformed(Unknown Source)
		at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:311)
		at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:243)
		at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
		at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
		at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
		at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
		at java.base@17.0.5/java.security.AccessController.executePrivileged(AccessController.java:776)
		at java.base@17.0.5/java.security.AccessController.doPrivileged(AccessController.java:399)
		at java.base@17.0.5/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
		at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
		at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
		at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
		at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
		at com.intellij.ide.IdeEventQueue$$Lambda$626/0x000000010071a280.compute(Unknown Source)
		at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
		at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
		at com.intellij.ide.IdeEventQueue$$Lambda$625/0x000000010071a038.run(Unknown Source)
		at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
		at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
		at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
		at com.intellij.ide.IdeEventQueue$$Lambda$624/0x0000000100719df0.run(Unknown Source)
		at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
		at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
		at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
		at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
		at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
		at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
		at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
		at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```

**Comment by kings1990** [comment]
不影响使用吧
