### ISSUE TITLE
POST请求接受json的实体类中包含枚举类型字段时无法生成请求参数

### ISSUE THREAD

**Issue by afezeria** [dromara/fast-request#27]
### 当前使用版本(Current Version)
2.1.0.2

### 重现步骤(Repeat steps)
代码如下，点击生成请求时body内容为空
```
@RestController
@RequestMapping("a")
public class AController {
    @PostMapping
    public String hello(@RequestBody @Valid ARequest request) {
        return "default";
    }

    @Data
    static class ARequest {
        private String name;
        private EnumType type;
    }

    enum EnumType {T1, T2, T3, T4}
}
```

### 报错信息(Error Message)
```
java.lang.ClassCastException: class java.lang.String cannot be cast to class io.github.kings1990.plugin.fastrequest.util.KV (java.lang.String is in module java.base of loader 'bootstrap'; io.github.kings1990.plugin.fastrequest.util.KV is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @6219f35a)
	at io.github.kings1990.plugin.fastrequest.view.FastRequestToolWindow.convertArrayToMap(FastRequestToolWindow.java:2059)
	at io.github.kings1990.plugin.fastrequest.view.FastRequestToolWindow.convertToMap(FastRequestToolWindow.java:2035)
	at io.github.kings1990.plugin.fastrequest.view.FastRequestToolWindow.convertToMap(FastRequestToolWindow.java:2018)
	at io.github.kings1990.plugin.fastrequest.view.FastRequestToolWindow.bodyParamMapToJson(FastRequestToolWindow.java:1846)
	at io.github.kings1990.plugin.fastrequest.view.FastRequestToolWindow.refresh(FastRequestToolWindow.java:1185)
	at io.github.kings1990.plugin.fastrequest.view.FastRequestToolWindow$RetryAction.actionPerformed(FastRequestToolWindow.java:3210)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:172)
	at com.intellij.openapi.actionSystem.impl.ActionButton.lambda$performAction$0(ActionButton.java:151)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:265)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:151)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:433)
	at java.desktop/java.awt.Component.processEvent(Component.java:6419)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5029)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2790)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:820)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:757)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:498)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by kings1990** [comment]
update to 2.1.1
